name: Manual trigger alarm

on:
  workflow_dispatch:
    inputs:
      DISCORD_WEBHOOK_TOKEN:
        description: "DISCORD_WEBHOOK_TOKEN"
        required: true
        type: string
      DISCORD_WEBHOOK_ID:
        description: "DISCORD_WEBHOOK_ID"
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_ID: ${{ github.event.inputs.DISCORD_WEBHOOK_ID }}

    strategy:
      matrix:
        node-version: [20]

    steps:
    - run: echo "🎉 The job was triggered by a ${{ github.event_name }} event."

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout free-games-alerts
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Mask tokens
      run: |
        DISCORD_WEBHOOK_TOKEN=$(jq -r '.inputs.DISCORD_WEBHOOK_TOKEN' $GITHUB_EVENT_PATH)
        echo ::add-mask::$DISCORD_WEBHOOK_TOKEN
        echo DISCORD_WEBHOOK_TOKEN=$DISCORD_WEBHOOK_TOKEN >> $GITHUB_ENV

    - name: Run send_free_games_alert script
      run: npm run send_free_games_alert
