name: Manual trigger alarm

on:
  workflow_dispatch:
    inputs:
      DISCORD_WEBHOOK_TOKEN:
        description: "The token that is needed to make calls to the webhook of discord."
        required: true
        default: "<DISCORD_WEBHOOK_TOKEN>"
      DISCORD_WEBHOOK_ID:
        description: "The id that points to the webhook of discord that you want to make the call."
        required: true
        default: "<DISCORD_WEBHOOK_ID>"

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_TOKEN: ${{ github.event.inputs.DISCORD_WEBHOOK_TOKEN }}
      DISCORD_WEBHOOK_ID: ${{ github.event.inputs.DISCORD_WEBHOOK_ID }}

    strategy:
      matrix:
        node-version: [20]

    steps:
    - run: echo "🎉 The job was triggered by a ${{ github.event_name }} event."

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout free-games-alerts
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Run send_free_games_alert script
      run: npm run send_free_games_alert
