name: Manual trigger alarm

on:
  workflow_dispatch:
    inputs:
      DISCORD_WEBHOOK_TOKEN:
        description: "DISCORD_WEBHOOK_TOKEN"
        required: true
        type: string
      DISCORD_WEBHOOK_ID:
        description: "DISCORD_WEBHOOK_ID"
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - run: echo "🎉 The job was triggered by a ${{ github.event_name }} event."

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout free-games-alerts
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --force

      - name: Mask tokens
        run: |
          DISCORD_WEBHOOK_TOKEN=$(jq -r '.inputs.DISCORD_WEBHOOK_TOKEN' $GITHUB_EVENT_PATH)
          echo ::add-mask::$DISCORD_WEBHOOK_TOKEN
          echo DISCORD_WEBHOOK_TOKEN=$DISCORD_WEBHOOK_TOKEN >> $GITHUB_ENV
          DISCORD_WEBHOOK_ID=$(jq -r '.inputs.DISCORD_WEBHOOK_ID' $GITHUB_EVENT_PATH)
          echo ::add-mask::$DISCORD_WEBHOOK_ID
          echo DISCORD_WEBHOOK_ID=$DISCORD_WEBHOOK_ID >> $GITHUB_ENV

      - name: Run send_free_games_alert script
        run: npm run send_free_games_alert

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./src/data/games.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "add new games to the storage"
          git push
