name: Run Weekly Script
on:
  schedule:
    - cron: '0 15 * * 5' # Every Friday at 15:00 UTC
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
      DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}

    strategy:
      matrix:
        node-version: [20]

    steps:
    - run: echo "🎉 The job was triggered by a ${{ github.event_name }} event."

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout free-games-alerts
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Run send_free_games_alert script
      run: npm run send_free_games_alert

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ./src/data/games.json
        git commit -m "add new games to the storage"
        git push
